language: cpp

compiler:
  - clang
  - gcc

before_install:
  # TODO: remove the following when Travis has C++11-feature-complete G++.
  - scripts/update_compilers.bash
  # TODO: remove the following when Travis has CMake newer than 2.8.12.
  - scripts/update_cmake.bash

script:
  - cd build && cmake .. && make && make install

os:
  - linux
  - osx
